/* Copyright 2026 上海如静知华信息科技有限公司 */
package cn.zhuatech.auditagent;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.MockMvc; import java.util.regex.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class AuditAgentApiIntegrationTests {
    @Autowired MockMvc mvc; private String operatorToken; private String plannerToken;
    @BeforeEach void login()throws Exception{operatorToken=token("operator","Demo@2026");plannerToken=token("planner","Demo@2026");}
    private String token(String u,String p)throws Exception{String json=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"username\":\""+u+"\",\"password\":\""+p+"\"}")).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();Matcher matcher=Pattern.compile("\\\"token\\\":\\\"([^\\\"]+)\\\"").matcher(json);if(!matcher.find())throw new AssertionError("登录响应中缺少 token");return matcher.group(1);}
    @Test void operatorCanReadShopfloorDashboard()throws Exception{mvc.perform(get("/api/shopfloor/dashboard").header("Authorization","Bearer "+operatorToken)).andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true)).andExpect(jsonPath("$.data.metrics[0].label").value("审计样本总量"));}
    @Test void plannerCanReadWorkRecords()throws Exception{mvc.perform(get("/api/admin/work-orders").header("Authorization","Bearer "+plannerToken)).andExpect(status().isOk()).andExpect(jsonPath("$.data.length()").value(3));}
    @Test void operatorCanSubmitProductionReport()throws Exception{mvc.perform(post("/api/shopfloor/work-orders/1/reports").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"operationName\":\"样本测试\",\"goodQty\":2,\"defectQty\":1,\"remark\":\"审计证据完整\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.message").value("反馈提交成功")).andExpect(jsonPath("$.data.completedQty").value(58));}
    @Test void operatorCanRunLocalAgentPreview()throws Exception{mvc.perform(post("/api/shopfloor/agent-preview").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"objective\":\"执行采购审计\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.runtime").value("local-audit-demo")).andExpect(jsonPath("$.data.steps.length()").value(3));}
    @Test void operatorCanRecommendAuditSample()throws Exception{mvc.perform(post("/api/shopfloor/audit-sampling").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"populationName\":\"采购付款总体\",\"populationSize\":1000,\"anomalyRate\":0.12,\"materialityScore\":80,\"controlWeakness\":true,\"previousFindings\":3}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.riskScore").value(61)).andExpect(jsonPath("$.data.recommendedSampleSize").value(200)).andExpect(jsonPath("$.data.assuranceLevel").value("MODERATE")).andExpect(jsonPath("$.data.strata.length()").value(4));}
    @Test void operatorCanCheckEvidenceReadiness()throws Exception{mvc.perform(post("/api/shopfloor/evidence-readiness").header("Authorization","Bearer "+operatorToken).contentType(MediaType.APPLICATION_JSON).content("{\"workpaperCode\":\"WP-2026-018\",\"requiredEvidence\":[\"合同\",\"验收单\",\"付款凭证\"],\"attachedEvidence\":[\"合同\",\"付款凭证\"],\"sourceTraceable\":false,\"reviewerAssigned\":true}"))
        .andExpect(status().isOk()).andExpect(jsonPath("$.data.state").value("INCOMPLETE"))
        .andExpect(jsonPath("$.data.completenessPercent").value(67))
        .andExpect(jsonPath("$.data.missingEvidence[0]").value("验收单"))
        .andExpect(jsonPath("$.data.remediationActions.length()").value(2));}
    @Test void anonymousRequestIsDenied()throws Exception{mvc.perform(get("/api/admin/dashboard")).andExpect(status().isForbidden());}
}
